apiVersion: v1
kind: Service
metadata:
  name: flask-node-deployment
spec:
  selector:
    app: flask-app
  ports:
  - name: http
    protocol: TCP
    port: 7777
    targetPort: 7777
  type: LoadBalancer
